### ISSUE TITLE
Use CF CC fields

### ISSUE THREAD

**Issue by netzih** [agileware/cf-stripe#2]
Is there a way to charge credit cards using the CF cc fields and not have to go through stripe hosted page?

Thanks

**Comment by agileware-justin** [comment]
Not currently, no. It uses the PHP library to communicate with Stripe.

**Comment by agileware-justin** [comment]
> Is there a way to charge credit cards using the CF cc fields and not have to go through stripe hosted page?

Apologies. I did not answer your question correctly. This plugin uses the Stripe javascript library and sends the credit card details directly to Stripe for processing without storing any details on the website hosting the form. It is implemented this way to be PCI compliant. Using this method a website is PCI SAQ A compliant, see https://stripe.com/docs/security/guide

<img width="673" alt="stripe" src="https://user-images.githubusercontent.com/58866555/108902024-b086be00-766f-11eb-9411-fcbb8ead8b86.png">
